### ISSUE TITLE
Lav side til electricity prices

### ISSUE THREAD

**Issue by AugustZachariae** [MalteMagnussen/satellite-energy-solutions#3]
Tænker vi kan smide det vi lavede til hackathon angående el priser op på el pris tappen under our services

**Comment by MalteMagnussen** [comment]
Hvordan skal det se ud?

**Comment by AugustZachariae** [comment]
Jeg vil gerne have det skal se ud som
![image](https://user-images.githubusercontent.com/57957239/69614008-c2c01980-1032-11ea-886a-4d8c855aa45a.png)

**Comment by MalteMagnussen** [comment]
Alright. Giver det et skud.
